name: TheLanguageConcept
favicon: null
layout_spectrum: 0.94184
typography_spectrum: 0.4048
title: TheLanguageConcept
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0379ff'
    - '#c5b8ff'
    - '#b1e6ff'
    - '#8d8aff'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
