name: TheLanguageConcept
favicon: null
layout_spectrum: 0.99212
typography_spectrum: 0.49279
title: TheLanguageConcept
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0379ff'
    - '#c5b8ff'
    - '#b1e6ff'
    - '#8d8aff'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
