name: TheLanguageConcept
favicon: null
layout_spectrum: 0.92634
typography_spectrum: 0.4048
title: TheLanguageConcept
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfef3'
    - '#007aad'
    - '#090e12'
    - '#c0c5c9'
    - '#363f27'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
